name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: npm run build:shrunk-test && mv -r dist shrunk-test-dist && npm run build:shrunk-prod && mv -r dist shrunk-prod-dist

    - name: Archive Production Build
      run: zip -r shrunk-test-dist.zip shrunk-test-dist/ && zip -r shrunk-prod-dist.zip shrunk-prod-dist/

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: shrunk-test-dist.zip shrunk-prod-dist.zip
